server:
  port: 8099

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:19092
      enable-auto-commit: true

clickhouse:
  endpoint: http://localhost:8123
  database: default
  username: default
  password: ""
  connect-timeout: 30000
  socket-timeout: 60000
  max-connections: 10
  compress: true

