server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:duytc}
    password: ${DB_PASSWORD:}
    hikari:
      auto-commit: true
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 60000
      max-lifetime: 200000
      connection-timeout: 20000
      pool-name: '[ CONNECT ] ===>'

  liquibase:
    enabled: true
    change-log: classpath:liquibase/main-changelog.yml
    clear-checksums: true

  security:
    access-token: ${JWT_ACCESS_SECRET:}
    access-token-time: ${JWT_ACCESS_TTL_MS:900000}
    refresh-token: ${JWT_REFRESH_SECRET:}
    refresh-token-time: ${JWT_REFRESH_TTL_MS:604800000}
    verified-token: ${JWT_VERIFIED_SECRET:}
    verified-token-time: ${JWT_VERIFIED_TTL_MS:600000}

  freemarker:
    template-loader-path: classpath:/templates/mail
    suffix: .ftlh
    cache: true
    charset: UTF-8

springdoc:
  api-docs:
    url-product: http://localhost:8080
    url-dev: http://localhost:8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.example.springsecurity.requests, org.example.springsecurity.responses
  type-handlers-package: org.example.springsecurity.util
  mapper-locations: classpath:/mybatis/*.xml

cors:
  allowed:
    origins:
      - http://localhost:4200
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    headers:
      - Content-Type
      - Authorization
  permit-all:
    endpoint:
      - /swagger-ui/**
      - /v3/api-docs/**
      - /swagger-resources/**
      - /webjars/**
      - /api/auth/login
      - /api/auth/signup
      - /api/auth/reset-token
      - /api/auth/forgot-password
      - /api/auth/validate-token
